#!/usr/bin/env bash
# Sets up a Solana development environment and generates a starter Anchor workspace.
#
# Run this on your own machine. It needs network access to release.anza.xyz,
# sh.rustup.rs, and a Solana RPC endpoint.
#
# Usage:  ./scripts/setup-solana-dev.sh [workspace-name]

set -euo pipefail

WORKSPACE="${1:-scratch}"
say() { printf '\n\033[1m==> %s\033[0m\n' "$*"; }
have() { command -v "$1" >/dev/null 2>&1; }

# ## Prerequisites
say "Checking prerequisites"

if ! have rustc; then
  say "Installing Rust"
  curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
  # shellcheck disable=SC1091
  . "$HOME/.cargo/env"
else
  echo "rust:   $(rustc --version)"
fi

if ! have node; then
  echo "ERROR: Node.js not found. Install Node 18+ (nvm recommended), then re-run." >&2
  exit 1
fi
echo "node:   $(node --version)"

# Anchor's generated tests default to yarn.
if ! have yarn; then
  say "Installing yarn"
  npm install -g yarn
fi
echo "yarn:   $(yarn --version)"

# ## Solana CLI
if ! have solana; then
  say "Installing Solana CLI (Anza)"
  sh -c "$(curl -sSfL https://release.anza.xyz/stable/install)"
  export PATH="$HOME/.local/share/solana/install/active_release/bin:$PATH"
  echo
  echo "NOTE: add this to your shell profile:"
  echo '  export PATH="$HOME/.local/share/solana/install/active_release/bin:$PATH"'
fi
echo "solana: $(solana --version)"

# ## Anchor
if ! have avm; then
  say "Installing avm (Anchor version manager) — this compiles from source, give it a few minutes"
  cargo install --git https://github.com/coral-xyz/anchor avm --force
fi

if ! have anchor; then
  say "Installing latest Anchor"
  avm install latest
  avm use latest
fi
echo "anchor: $(anchor --version)"

# ## Devnet + keypair
say "Configuring devnet"
solana config set --url devnet

if [ ! -f "$HOME/.config/solana/id.json" ]; then
  say "Generating a keypair"
  echo "Save the seed phrase it prints. This is a DEV keypair — never fund it with real money."
  solana-keygen new --no-bip39-passphrase
fi
echo "wallet: $(solana address)"
echo "balance: $(solana balance)"

say "Requesting a devnet airdrop"
# The public faucet rate-limits aggressively; failure here is normal and not fatal.
solana airdrop 2 || echo "Airdrop failed (rate limited). Use https://faucet.solana.com or retry later."

# ## Scaffold
if [ -d "$WORKSPACE" ]; then
  echo "Directory '$WORKSPACE' already exists — skipping scaffold generation."
else
  say "Generating Anchor workspace: $WORKSPACE"
  # Generated by the real toolchain rather than hand-written, so the versions
  # and layout match whatever Anchor you just installed.
  anchor init "$WORKSPACE"
fi

say "Done"
cat <<'NEXT'
Next:
  cd <workspace>
  anchor build
  anchor test          # spins up a local validator, deploys, runs the TS tests

If `anchor test` passes, your toolchain is working. That is the week 1 gate in
docs/00-prep-plan.md — do not move on until it is green.
NEXT
